# Generated by Django 3.2.13 on 2022-06-23 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0)),
                ('age', models.SmallIntegerField(default=60)),
                ('phone_number', models.CharField(max_length=20)),
                ('identity_number', models.CharField(max_length=30)),
                ('room_id', models.SmallIntegerField()),
                ('register_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.SmallIntegerField(choices=[(0, 'Admin'), (1, 'Elder')], default=1)),
            ],
        ),
    ]
